### ISSUE TITLE
Did not work in qutebrowser when domain is already blocked using 'hosts' file

### ISSUE THREAD

**Issue by HiTuX** [dybdeskarphet/privacy-redirector#1]
Hi, 
this script did not work  in qutebrowser if the damain is already blocked in `hosts` file. I used to use Privacy Redirect in Brave browser and it works fine. Is there any chance to make it work without removing the domain from `hosts` file.

**Comment by dybdeskarphet** [comment]
I haven't tried the script with other browsers yet (sorry, my fault). i'll test the script with other browsers and fix the problem that you're talking about at the weekend. thanks for the feedback :)

**Comment by dybdeskarphet** [comment]
@HiTuX so i searched thorough the workarounds and in conclusion, a local server has to be running in the background for your `hosts` redirections and `hosts` file has to be changed according to the local server configurations like this example:
```
127.0.0.77:68433/instagram      www.instagram.com
127.0.0.77:68433/reddit         www.reddit.com
127.0.0.77:68433/twitter        twitter.com
...
```

and i don't have the skillset for that :/ though i'll leave this issue open for the possible future fixes
