### ISSUE TITLE
Feature Request: Instance Blacklist/Whitelist

### ISSUE THREAD

**Issue by MintMain21** [dybdeskarphet/privacy-redirector#11]
By default, most of the redirects (YouTube/Twitter specifically) use FarSide to ensure that they always redirect to the most readily available and stable instance, acting as a sort of wild card.

However, some instances have preferences I'm not a fan of, such as default languages or disabled features. 

I would appreciate being able to set up a blacklist/whitelist of instances FarSide uses, if possible.

Alternatively, being able to disable FarSide for individual redirects and instead use a pool of pre-chosen instances like with Bibliogram or Proxitok would be welcome as well. It seems when Farside Support was added that this option was dropped for YouTube/Twitter in favor of FarSide. I think there's value in keeping it an option though, even though FarSide is clearly more efficient.

**Comment by dybdeskarphet** [comment]
I started working on it after seeing your issue. It is going to look like this:

```javascript
/*
  ___  _   _        ___  _____ _____ 
 / _ \| \ | |      / _ \|  ___|  ___|
| | | |  \| |_____| | | | |_  | |_   
| |_| | |\  |_____| |_| |  _| |  _|  
 \___/|_| \_|      \___/|_|   |_|    

CHANGE THE RELEVANT VALUE TO "false" TO
DISABLE THE REDIRECTION FOR THAT
PARTICULAR SITE */
// 			REDIRECTON	FARSIDE
// 			----------	-------
var fandom =	 	[true,		false];
var gtranslate =	[true,		true];
var hackernews = 	[true,		true];
var imdb = 		[true,		true];
var imgur = 		[true,		true];
var instagram = 	[true,		true];
var medium = 		[true,		true];
var quora = 		[true,		true];
var reddit = 		[true,		true];
var reuters = 		[true,		true];
var tiktok = 		[true,		true];
var twitter = 		[true,		true];
var wikipedia = 	[true,		true];
var youtube = 		[true,		true];

```

I'll try to finish it as soon as possible, thank you for your recommendation.
