### ISSUE TITLE
Bibliogram: Redirect only post and reel links.

### ISSUE THREAD

**Issue by MintMain21** [dybdeskarphet/privacy-redirector#12]
It is well documented that Bibliogram is currently unmaintained and abandoned by the developer, however there are still some key instances running, albeit they only work for posts and reels (IE: actual content). You can't redirect users pages, nor can you search for pages. 

Even so, basic redirections of posts and reels still work, but this script is currently hardwired to redirect *every* path to Instagram. 

I propose altering the code so only posts/reels are redirected, at least until a new developer takes over Bibliogram, or a proper alternative surfaces. 

Alternatively, this behavior could be a switch in the same vein as enabling Farside or individual sites.

**Comment by dybdeskarphet** [comment]
I agree that it would be practical to make Instagram redirection to only redirect posts and reels but as you said, Bibliogram has been discontinued and I don't think post redirections are going to work for a long time. That's why I'm not planning to enable it. But I really appreciate your feedback.
