### ISSUE TITLE
captchas no longer working

### ISSUE THREAD

**Issue by Konfekt** [dybdeskarphet/privacy-redirector#15]
Since the latest update, (google) captchas to prove that one is not human are only loaded after disabling this user script.

**Comment by Konfekt** [comment]
Other than that, a very useful script. Kudos!

**Comment by dybdeskarphet** [comment]
@Konfekt I realized that not only Captchas but also Google Drive, Google Maps and other Google Services doesn't work with ``Google -> Searx`` redirection. I'll fix it as soon as possible. Thank you for the feedback!

**Comment by dybdeskarphet** [comment]
@Konfekt Also you don't have to disable the whole script, you can change the redirection value to false for ``google`` redirection:

``` javascript
...
let fandom = [true, true];
let google = [false, true];
let gtranslate = [true, true];
...
```

**Comment by Konfekt** [comment]
Yes, thank you! In fact, I had this at some point, but how to ensure that an update does not override this setup?

**Comment by dybdeskarphet** [comment]
> Yes, thank you! In fact, I had this at some point, but how to ensure that an update does not override this setup?

@Konfekt Unfortunately, there is no way to keep your own settings after the update. The only solution is copying them into another file and replacing the default values after updates.
