### ISSUE TITLE
No Fandom Redirects?

### ISSUE THREAD

**Issue by MintMain21** [dybdeskarphet/privacy-redirector#19]
Fandom won't redirect. Furthermore, sites that should be redirected get this weird notification. 

![image](https://user-images.githubusercontent.com/91362684/227751413-cd413b0d-b774-47c6-8f8a-1ea75334ba79.png)

Here's the URL to see for yourself.  https://spongebob.fandom.com/wiki/Encyclopedia_SpongeBobia

**Comment by dybdeskarphet** [comment]
Oh no I forgot the debug mode on, really sorry for the inconvenience. I'm fixing both of them right away
