### ISSUE TITLE
Suggestions regarding Bibliogram.

### ISSUE THREAD

**Issue by MintMain21** [dybdeskarphet/privacy-redirector#20]
While it's good to bring attention to the fact that Bibliogram is, effectively, an abandoned project, there are still a few instances running and reasons for people to use it over Instagram proper. 

Unfortunately, out of the three instances recognized by Farside, one is a broken link. This instances (bibliogram.1d4.us) is also one of the two instances listed as a backup option with Farside disabled. 

So I propose the following updates.

1. Disable Bibliogram Farside by default.

2. remove bibliogram.1d4.us from the default list, and replace it with bibliogram.froth.zone

3. Add the option to disable the "bibliograph is abandoned" warning (anyone who would willingly enable bibliogram is likely aware of the project's condition.

**Comment by dybdeskarphet** [comment]
I'll look into it at the weekend, thanks for the feedback

**Comment by dybdeskarphet** [comment]
Restored with f2ced40.
