### ISSUE TITLE
Optionally support farside's redirect-preserving "/_/" links

### ISSUE THREAD

**Issue by achadwick** [dybdeskarphet/privacy-redirector#24]
Hi Arda! Thanks for making this script. I'm testing it out in [Mull](https://divestos.org/pages/our_apps#mull) on Android, as a replacement for the UntrackMe app.

Since benbusby/farside@932f3bbcab9be82aafb487d7890fde83b2210a7b in late Jan 2022, Farside has permitted links prefixed with `/_/`. These "redirect-preserving" links issue the redirect with a JS fragment, in a way that keeps the redirection page in the history. If an instance is down, or is testing falsely, a different instance can be chosen by pressing the browser's back button. I find it quite useful!

Please can you add a variable to append the `/_` when `farsideInstance` is used? The same effect can be achieved by editing that variable, but it might be cleaner to do as a boolean.

It would be quite sensible as default behaviour, but that's up to you! :D

**Comment by dybdeskarphet** [comment]
That seems useful, I'll add it in the next update, thanks
