### ISSUE TITLE
Twitter redirect doesn't work properly due to recent Twitter changes

### ISSUE THREAD

**Issue by muchqs** [dybdeskarphet/privacy-redirector#25]
Recently Twitter changed so you have to log in to view tweets.

If you open a profile without log in like
`https://twitter.com/elonmusk`

Twitter changes URL immediately to the login page
`https://twitter.com/i/flow/login?redirect_after_login=%2Felonmusk`

And the redirect only changes the domain so it becomes like this
`https://nitter.net/i/flow/login?redirect_after_login=%2Felonmusk`
which obviously doesn't work.

When it should be 
`https://nitter.net/elonmusk`

Could you fix this please?
Thanks.

**Comment by dybdeskarphet** [comment]
I'll fix this with the [solution](https://github.com/dybdeskarphet/privacy-redirector/commit/164f373cc5320f4f17e5de1cd50cc9c463264ce0) of @llExSt, thanks for the feedback.
