### ISSUE TITLE
Tubo Redirection (alternate YouTube frontend)

### ISSUE THREAD

**Issue by MintMain21** [dybdeskarphet/privacy-redirector#27]
[Tubo](https://github.com/migalmoreno/tubo) is an alternate YouTube frontend based on Newpipe, and as such can also proxi content from Soundcloud, Peertube, etc. A handy alternative imo.

**Comment by MintMain21** [comment]
Update: I wrote my own temp script for Tubo redirection. [Hopefully it helps](https://github.com/MintMain21/Tubo-Redirect-Userscript).

**Comment by dybdeskarphet** [comment]
I'll try to add it both for YouTube and SoundCloud after I determine the pathnames and queries. Your script may help, thank you for the feedback.
