### ISSUE TITLE
IMDb redirection does not work on Bromite

### ISSUE THREAD

**Issue by mizzunet** [dybdeskarphet/privacy-redirector#28]
As the title says, any IMDb links simply opens IMDb

**Comment by joshcangit** [comment]
Actually, the hostname on mobile is `m.imdb.com`.
Just need to add a line to the appropriate `case`.

FYI, I now use Cromite instead.
<https://github.com/uazo/cromite>

**Comment by dybdeskarphet** [comment]
I'll fix it after I eat my breakfast. By the way, @mizzunet I highly recommend you to not use Bromite, it's abandoned. As @joshcangit said, use Cromite instead.
