### ISSUE TITLE
Feature request: Exclude certain sites from the redirect

### ISSUE THREAD

**Issue by Dyras** [dybdeskarphet/privacy-redirector#3]
Hello! I'm in love with this script, as I find it works better than the Privacy Redirect extension.

However, I wish I could exclude YouTube from the redirection. Primarily because I use scripts for YouTube for screenshots, larger window, etc. 

Would a setting like this be possible to implement? :)

**Comment by dybdeskarphet** [comment]
Hello,
Thank you for your recommendation. I wanted to add an option for that and now I did. After updating the script, you can disable redirections by changing the values below the big ON-OFF title. I initially wanted to add a graphical way to do this but it's just a script and not an extension so I think this is enough for a little script :)
