### ISSUE TITLE
Disabling Farside for Twitter Leads to Redirect Error

### ISSUE THREAD

**Issue by maikcheck** [dybdeskarphet/privacy-redirector#36]
I’ve been using this script for months and it’s fantastic, but I did run into this small issue. When disabling Farside for Twitter, the Nitter instance’s URL that I’m redirected to always contains an encoded slash instead of the slash itself. For example: 

https://nitter.d420.de/elonmusk%2Fmedia

Redirection is successful only if the URL I’m redirecting from doesn’t contain anything after a user’s Twitter handle, slashes and all.

(I’m using Violentmonkey 2.16.0 via Firefox 119.0.1)

**Comment by dybdeskarphet** [comment]
I'll look into it, thanks for the feedback

**Comment by dybdeskarphet** [comment]
Can you check if it still happens? @maikcheck

**Comment by dybdeskarphet** [comment]
Can you give me an example input and output URL so I can recreate the issue?

**Comment by dybdeskarphet** [comment]
Can you try this one from my branch: https://github.com/dybdeskarphet/privacy-redirector/raw/dybdeskarphet/privacy-redirector.user.js

**Comment by dybdeskarphet** [comment]
Perfect, thanks
