### ISSUE TITLE
Doesn't seem to work properly for Instagram

### ISSUE THREAD

**Issue by Dyras** [dybdeskarphet/privacy-redirector#4]
Browser: Brave
Addons: Cookie AutoDelete, CSS Exfil Protection, Disqus Auto Expander, I don't care about cookies, Violentmonkey
Scripts: Only Privacy Redirector
Country: Sweden

Hello! When I click an Instagram link, I'm sent to a 404 page instead of the actual site. Example:
https://www.instagram.com/pewdiepie/
Takes me to
https://bibliogram.pussthecat.org/u/accounts/login/?next=/pewdiepie/

Is this a known issue? Or a conflict with something else?

**Comment by dybdeskarphet** [comment]
I have this problem too. The reason why it happens is: When you enter a
Instagram profile without logging in to your Instagram account, it quickly
adds parameters about that situation.

I'll fix it today or tomorrow. Thanks for reporting it!

12 Mar 2022 Cmt 14:24 tarihinde Dyras ***@***.***> şunu yazdı:

**Comment by dybdeskarphet** [comment]
@Dyras I think I fixed it now, update and see if it works!

**Comment by Dyras** [comment]
Seems to work! Thanks!
