### ISSUE TITLE
Feature request: Use Farside instances

### ISSUE THREAD

**Issue by martru118** [dybdeskarphet/privacy-redirector#5]
There are some instances in the script that are dead, like `alefvanoon.xyz` and `silkky.cloud` for example (there may be more). It gets a little annoying that I have to type the link again whenever I get redirected to a dead instance.

Instead, use [farside.link](https://farside.link) for redirects. It automatically checks for online instances and there is no need to [hardcode a list of instances](https://github.com/benbusby/farside#demo).

**Comment by dybdeskarphet** [comment]
Thank you so much, I really needed something like farside. I removed the dead instances for this update but I'm definitely adding farside link in the next update.
