### ISSUE TITLE
Bug: YouTube embeds breaks with this script enabled

### ISSUE THREAD

**Issue by RoonMoonlight** [dybdeskarphet/privacy-redirector#51]
Hello, when there is embed videos on some page, the video displays Piped page instead of embed videos. Can you look what happened?
![Screenshot_20240229_092654_Fennec](https://github.com/dybdeskarphet/privacy-redirector/assets/25527589/303effc0-5d04-4a74-9975-b17940cb7819)

**Comment by dybdeskarphet** [comment]
Related to #52, I'll look into it. Thanks for the feedback.
