### ISSUE TITLE
twitter redirect stop working

### ISSUE THREAD

**Issue by SleepDaemon** [dybdeskarphet/privacy-redirector#55]
might have to do with the fact twitter links are now auto redirect to x.com instead of twitter.com

**Comment by SleepDaemon** [comment]
The fix is to add ```@match *//x.com/*``` and also include `case "x.com":` under the switch case

**Comment by dybdeskarphet** [comment]
Fixing it, thanks

**Comment by dybdeskarphet** [comment]
@SleepDaemon can you check if the 1.5.8 fixes this issue?

**Comment by SleepDaemon** [comment]
> @SleepDaemon can you check if the 1.5.8 fixes this issue?

You include x.com twice in the `@match` area

**Comment by SleepDaemon** [comment]
other than that its seems working fine

**Comment by dybdeskarphet** [comment]
Yeah, I added `// @match *://*.x.com/*` to include `mobile` subdomain. I'm not sure if it's still in use but there's no harm in taking precautions. Closing the issue then.
