### ISSUE TITLE
[Enhancement] Mozhi Translate  

### ISSUE THREAD

**Issue by BloodDragooner2** [dybdeskarphet/privacy-redirector#56]
Hi! Mozhi, [here](https://codeberg.org/aryak/mozhi), is a privacy respecting frontend for many translation engines such as: 
Google
Reverso
DeepL
LibreTranslate
Yandex
MyMemory
DuckDuckGo
or all of these at once

Hope you consider it! Love the script :)

**Comment by dybdeskarphet** [comment]
I'm working on another project right now and considering that it supports 6 translation engines, it's going to take some work, but I'll add it whenever I can, probably in a week or so.

**Comment by joshcangit** [comment]
So Mozhi is a fork of simplytranslate.
I hope the instances don't use POST requests.

I think JavaScript cannot access POST request data.
For that, the script can redirect but the text you want to translate will then be lost.

**Comment by dybdeskarphet** [comment]
@joshcangit I actually figured it out how to use the endpoints but I was just curious about the second condition block that I mention in your old old PR

**Comment by joshcangit** [comment]
Talking about the if and else if in the `redirectGTranslate()` function?

The if part is obviously for when the pathname logic is different between Google Translate and Lingva.

The else if part is for when the pathname logic is the same.
Then the .replace() method is to change every "+" in the search query to " " spaces which seems to work better.

**Comment by dybdeskarphet** [comment]
@joshcangit I see, but does Google Translate use `/` instead of `&` in some cases? If there are no such cases, I'll delete it.

**Comment by joshcangit** [comment]
The logic of the search query is made before redirecting to Lingva.
Such as when using Google Translate from the search or address bar on the browser main toolbar.

The "/word/word/word" is the new logic used by Google Translate.

The "?key1=value&key2=value" is the old logic which I had to change it to that new logic to make it work reliably even after redirecting to Lingva.

**Comment by dybdeskarphet** [comment]
@joshcangit Oh, I see. Thank you so much, I'll reconfigure the Mozhi according to it.

**Comment by dybdeskarphet** [comment]
Added with 5a628352b83df1b77823b55db48e958a2cd85065
