### ISSUE TITLE
Add support for SkunkyArt

### ISSUE THREAD

**Issue by kamekku14** [dybdeskarphet/privacy-redirector#57]
[SkunkyArt](https://git.macaw.me/skunky/SkunkyArt) is an alternative frontend for DeviantArt, written in Go.

Instances:
- https://skunky.ebloid.ru/art (Official)
- https://skunky.clovius.club/
- https://skunky.bloat.cat/
- https://skunkyart.frontendfriendly.xyz/
- https://skunkyart.lumaeris.com/
- https://art.bloat.cat/

**Comment by dybdeskarphet** [comment]
Added with 3bde339c4341a617c2443ef67c90b9546ed800ec
