### ISSUE TITLE
Add support for Priviblur

### ISSUE THREAD

**Issue by kamekku14** [dybdeskarphet/privacy-redirector#58]
[Priviblur](https://github.com/syeopite/priviblur) is an alternative frontend to Tumblr with a touch of modern design.

Instances:   
- https://pb.bloat.cat/
- https://tb.opnxng.com/
- https://priviblur.pussthecat.org/
- https://priviblur.thebunny.zone/
- https://priviblur.gitro.xyz/
- https://priviblur.canine.tools/

**Comment by dybdeskarphet** [comment]
Added with b3568c877494fb9c432d68bc29972c9fe2b47827
